-- MySQL Script generated by MySQL Workbench
-- Tue Apr  7 13:59:40 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS sakuraracing ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS sakuraracing DEFAULT CHARACTER SET utf8 ;
USE sakuraracing ;

-- -----------------------------------------------------
-- Table sakuraracing.users
-- -----------------------------------------------------
DROP TABLE IF EXISTS sakuraracing.users ;

CREATE TABLE IF NOT EXISTS sakuraracing.users (
  id INT NOT NULL AUTO_INCREMENT,
  nome VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  senha VARCHAR(255) NOT NULL,
  PRIMARY KEY (id))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table sakuraracing.corredores
-- -----------------------------------------------------
DROP TABLE IF EXISTS sakuraracing.corredores ;

CREATE TABLE IF NOT EXISTS sakuraracing.corredores (
  id INT NOT NULL AUTO_INCREMENT,
  nome VARCHAR(255) NOT NULL,
  turma VARCHAR(255) NOT NULL,
  PRIMARY KEY (id))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table sakuraracing.voltas
-- -----------------------------------------------------
DROP TABLE IF EXISTS sakuraracing.voltas ;

CREATE TABLE IF NOT EXISTS mydb.voltas (
  id_volta INT NOT NULL AUTO_INCREMENT,
  data_hora_inicio DATETIME(3) NOT NULL,
  data_hora_fim DATETIME(3) NOT NULL,
  tempo_volta_ms INT NOT NULL,
  PRIMARY KEY (id_volta))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;